name: Scala CI

on:
- push
- pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
        - 2.13.4

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt ++${{ matrix.scala }} test
    - name: Publish to Maven Central Repository
      env:
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      if: ${{ env.GITHUB_PERSONAL_ACCESS_TOKEN != '' }}
      run: sbt ++${{ matrix.scala }} "set every Seq(sonatypeSessionName := \"Github Action ${{github.workflow}} ${{github.run_id}} ${{github.run_number}} ${{github.run_attempt}}\", publishTo := sonatypePublishToBundle.value)" publishSigned sonatypeBundleRelease
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
          ~/.coursier/
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
